config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users do
    resources :profile
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :houses do
    resources :comments
  end

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'my_houses', to: 'houses#mine', as: 'mine'

  get 'profile/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :house
end

app/models/concerns/filterable.rb
module Filterable
    extend ActiveSupport::Concern

    module ClassMethods
        def filter(filtering_params)
            results = self.where(nil)
            filtering_params.each do |key, value|
                results = results.public_send(key,value) if value.present?
            end
            results
        end
    end
end

app/models/house.rb
class House < ApplicationRecord
    include Filterable
    
    has_many :comments, dependent: :destroy

    validates :address, presence: true
    validates :available_date, presence: true
    validates :monthly_rent, presence: true
    validates :rooms_available, presence: true
    validates :current_occupants, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :houses, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        if session[:user_id]
            @current_user ||= User.find(session[:user_id])
        else
            @current_user = nil
        end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @house = House.find(params[:house_id])
        @comment = @house.comments.create(comment_params)
        redirect_to house_path(@house)
    end

    def destroy
        @house = House.find(params[:house_id])
        @comment = @house.comments.find(params[:id])
        @comment.destroy
        redirect_to house_path(@house)
    end
    
    private
        def comment_params
            params.require(:comment).permit(:commenter, :body)
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

    def index
        @houses = House.all
    end

    def show
        @house = House.find(params[:id])
    end

    def new
        @house = House.new
    end

    def create
        @house = House.new(house_params)

        if @house.save
            redirect_to @house
        else
            render 'new'
        end
    end

    def edit
        @house = House.find(params[:id])
    end

    def update
        @house = House.find(params[:id])

        if @house.update(house_params)
            redirect_to @house
        else
            render 'edit'
        end
    end

    def destroy
        @house = House.find(params[:id])
        @house.destroy

        redirect_to houses_path
    end

    def identify_user
        @user = current_user.email
    end

    def mine
        @houses = House.all
    end

    private
        def house_params

            params.require(:house).permit(:address, :available_date,
            :monthly_rent, :rooms_available, :current_occupants, :description, :owner)
        end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p>
    <strong>Commenter:</strong>
    <%= comment.commenter%>
</p>
<p>
    <strong>Comment:</strong>
    <%= comment.body%>
</p>

<p>
    <% if current_user && current_user.email == comment.commenter %>
    <%= link_to 'Delete Comment', [comment.house, comment],
                method: :delete,
                data: { confirm: 'Are you sure?' }%>
    <% end %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @house, @house.comments.build ], local: true) do |form| %>
<% if current_user %>
<p>
    <%= form.label :commenter%><br>
    <%= form.text_field :commenter, :value => current_user.email, :readonly => true%>
</p>
<p>
    <%= form.label :body%>
    <%= form.text_area :body%>
</p>
<p>
    <%= form.submit%>
</p>
<%end%>
<%end%>

app/views/home/index.html.erb
<% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
<% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
<% end %>

<p id=”notice”><%= notice %></p>

<h1>UW - Live Well!</h1>
<%= link_to "Available Houses", controller: "houses" %>

<% if current_user %>
<%= link_to 'Profile', controller: 'profile' %>
<% end %>

app/views/houses/_form.html.erb
<%= form_with(model: @house, local: true) do |form| %>

    <% if @house.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:
            </h2>
            <ul>
                <% @house.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :address%><br>
        <%= form.text_field :address%>
    </p>

    <p>
        <%= form.label :available_date%><br>
        <%= form.date_field :available_date, :value => Time.now.strftime('%Y-%m-%d'), min: Time.now.strftime('%Y-%m-%d') %>
    </p>

    <p>
        <%= form.label :monthly_rent %><br>
        <%= form.number_field :monthly_rent, min: 0 %>
    </p>

    <p>
        <%= form.label :rooms_available %><br>
        <%= form.number_field :rooms_available, min: 0, max: 20 %>
    </p>

    <p>
        <%= form.label :current_occupants %><br>
        <%= form.number_field :current_occupants, min: 0, max: 20%>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_area :description%>
    </p>
    
    <p>
        <% if current_user %>
            <%= form.label :owner %><br>
            <%= form.text_field :owner, :value => current_user.email, :readonly => true%>
        <% end %>
    </p>

    <p>
        <% if current_user %>
            <%= form.submit %>
        <% else %>
            <p>Unregistered users cannot create houses.</p>
            <%= link_to 'Sign Up', signup_path %> or
            <%= link_to 'Sign In', login_path %>
        <% end %>
    </p>
<% end %>

app/views/houses/edit.html.erb
<h1>Edit House</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Available Houses</h1>

<table>
    <tr>
        <th>Address</th>
        <th>Monthly Rent</th>
        <th>Available Date</th>
    </tr>
    
    <% @houses.each do |house| %>
    <tr>
        <td><%= house.address %></td>
        <td><%= house.monthly_rent %></td>
        <td><%= house.available_date %></td>
        <td><%= link_to 'Show', house_path(house) %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Delete', house_path(house),
                method: :delete,
                data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
</table>

<%= link_to 'New House', new_house_path %>
<%= link_to 'Home', controller: 'home' %>

app/views/houses/mine.html.erb
<h1>My Houses</h1>

<table>
    <tr>
        <th>Address</th>
        <th>Monthly Rent</th>
        <th>Available Date</th>
    </tr>
    
    <% @houses.each do |house| %>
    <tr>
        <% if current_user.email == house.owner %>
        <td><%= house.address %></td>
        <td>$<%= house.monthly_rent %></td>
        <td><%= house.available_date %></td>
        <td><%= link_to 'Show', house_path(house) %></td>
        <td><%= link_to 'Edit', edit_house_path(house) %></td>
        <td><%= link_to 'Delete', house_path(house),
                method: :delete,
                data: {confirm: 'Are you sure?'} %></td>
        <% end %>
    </tr>
    <% end %>
</table>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= form_with scope: :house, url: houses_path, local: true do |form| %>

    <% if @house.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:
            </h2>
            <ul>
                <% @house.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <p>
        <%= form.label :address %><br>
        <%= form.text_field :address %>
    </p>

    <p>
        <%= form.label :available_date%><br>
        <%= form.date_field :available_date, :value => Time.now.strftime('%Y-%m-%d'), min: Time.now.strftime('%Y-%m-%d') %>
    </p>

    <p>
        <%= form.label :monthly_rent %><br>
        <%= form.number_field :monthly_rent, min: 0 %>
    </p>

    <p>
        <%= form.label :rooms_available %><br>
        <%= form.number_field :rooms_available, min: 0, max: 20 %>
    </p>

    <p>
        <%= form.label :current_occupants %><br>
        <%= form.number_field :current_occupants, min: 0, max: 20%>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_area :description%>
    </p>

    <p>
        <%= form.submit %>
    </p>
<% end %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p>
    <strong>Address:</strong>
    <%= @house.address %>
</p>
<p>
    <strong>Available Date:</strong>
    <%= @house.available_date %>
</p>
<p>
    <strong>Monthly Rent:</strong>
    <%= @house.monthly_rent %>
</p>
<p>
    <strong>Rooms Available:</strong>
    <%= @house.rooms_available %>
</p>
<p>
    <strong>Current Occupants:</strong>
    <%= @house.current_occupants %>
</p>
<p>
    <strong>Description:</strong>
    <%= @house.description %>
</p>
<p>
    <strong>Owner:</strong>
    <%= @house.owner %>
</p>

<h2>Comments</h2>
<%= render @house.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form'%>

<%= link_to 'Edit', edit_house_path(@house) %> | 
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spike</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <% if current_user && current_user.email == user.email %>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>